### ISSUE TITLE
can-query-logic: Ignoring keys: $or.

### ISSUE THREAD

**Issue by MarcGodard** [canjs/feathers-query-logic#2]
Should the `feathers-query-logic` also deal with `$or`?

**Comment by MarcGodard** [comment]
Also getting this warning:

`can-query-logic: Ignoring keys: $select`

Anyone have an idea how to add these to remove the warning? I can do a PR, just need a little guidance.

**Comment by justinbmeyer** [comment]
Regarding `$or`, how are you using it?  `can-query-logic` has limited support for `$or`.

Regarding `$select`, I think you can add something like:

```js
if(special.$select){
  delete special.$select;
}
```

around here: https://github.com/canjs/feathers-query-logic/blob/master/feathers-query-logic.js#L9

**Comment by MarcGodard** [comment]
@justinbmeyer I use $or like this:

```
LocalesAvailable.getList({ $skip: 0, $limit: 1000000, $or: [{ active: false }, { active: true }] })
```

How the feathersJS docs use it.
