### ISSUE TITLE
$limit not always respected

### ISSUE THREAD

**Issue by MarcGodard** [canjs/feathers-query-logic#8]
#### Steps to reproduce:

- Build a component that displays a limited amount of records: `query: { active: true, $limit: 2 }`
- In another component make some of those records active
- The list grows while you add records above the limit

**Comment by justinbmeyer** [comment]
This is an issue with the real-time behavior of can-connect. It’s not solvable by set logic. I’ll explain more tomorrow.

**Comment by justinbmeyer** [comment]
A bit more information ...

We aren’t able to know if an item belongs in a paginated set, so the default heuristic is to just add any newly created items to the set. 

What would heuristic would you want to use?

**Comment by MarcGodard** [comment]
Not sure. Its not a major problem.

**Comment by justinbmeyer** [comment]
Ok, if you can come up with how you'd like it to behave, create an issue with that in `can-connect` and I'll write up how to patch your queryLogic's `.isMember()` and `.index()` so they return the right thing.

https://github.com/canjs/can-connect/blob/c1cbcfd56bf82488373fb89fc7bfaf8bcd94b035/real-time/real-time.js#L476

Hint ... if `.index( .. )` returns `-1`, the record won't be put in the list.  So you could just return `-1` if you somehow know it shouldn't show up.

**Comment by justinbmeyer** [comment]
closing this for now as we'll need a heuristic to progress on this issue.
